### ISSUE TITLE
12/5/2023  px-bench_12042023 – vanilla k8s  - test runAsUser: 2000 still only runs successfully when fio, run containers: runAsNonRoot: false

### ISSUE THREAD

**Issue by itmad-dev** [andrewh1978/px-bench#19]
#### Configure px-bench-user –uid 2000 on each worker node  

![2023-12-05_16-59-57](https://github.com/andrewh1978/px-bench/assets/13181490/aa546788-0944-4e40-b527-734dabc04cec)

#### px-bench-main.yml:  specify runAsUser: 2000 for containers:  fio, run  
![2023-12-05_17-00-47](https://github.com/andrewh1978/px-bench/assets/13181490/5bc28ed3-6795-4cfc-afa5-0f3caad35e13)

#### fio logs numerous permission denied  
![2023-12-05_17-07-11](https://github.com/andrewh1978/px-bench/assets/13181490/75c776a0-d9e8-4d8e-baec-f53ac787a2cc)
![2023-12-05_17-06-06](https://github.com/andrewh1978/px-bench/assets/13181490/bcb1d835-58ae-4f0a-8c10-96c371ae2244)

**Comment by andrewh1978** [comment]
I am reasonably sure this is fixed in https://github.com/andrewh1978/px-bench/pull/18

**Comment by itmad-dev** [comment]
I'll retest, I may have pulled this same day earlier than #18. Also testing TKGS.

**Comment by itmad-dev** [comment]
Same results with latest pull, vanilla k8s, TKGS: only runs successfully when runAsNonRoot: false. I can walk through both during tomorrow's meeting.
